defaults:
  - _self_

work_dir: ${hydra:runtime.cwd}

llm:
  model_id: gemini-2.5-flash
  system_prompt: "You are am expert medical agent who can segment volumes, analyze the resulting masks and make reports or some other insights based on what you find."
  temperature: 1.0

medical_models:
  bundle_root: models/
  device: "cuda"
  active_bundles:
    spleen: "spleen_ct_segmentation"
    # brain: "brats_mri_segmentation"
    multi_organ: "swin_unetr_btcv_segmentation"

tools:
  segmentation: true

sandbox:
  path: "./sandbox"

ui:
  type: cli